### ISSUE TITLE
ValueError: Filter must not be larger than the input: Filter: (8, 8) Input: (4, 84)

### ISSUE THREAD

**Issue by darren1231** [elix-tech/dqn#1]
I have installed everything I need in the environment, but there is still something error.
This error show: ValueError: Filter must not be larger than the input: Filter: (8, 8) Input: (4, 84)
And I run the code line by line, I found following line which caused the error.

model.add(Convolution2D(32, 8, 8, subsample=(4, 4), activation='relu', input_shape=(STATE_LENGTH, FRAME_WIDTH, FRAME_HEIGHT)))

I was wondering if you can help me fix this problem, I will be very appreciated. ^.^

**Comment by tokb23** [comment]
The order of `input_shape` changes depending on the backend you are using (tensorflow or theano).
You can change `image_dim_ordering` (`th` or `tf`) in the file `~/.keras/keras.json` and maybe it can fix the error.
Hope this helps!

**Comment by darren1231** [comment]
Thank you for your help.
It worked~~

For the person who might encounter the same problem.
Here is the content of the file.  Home/user_name/.keras/keras.json

{
    "image_dim_ordering": "th", 
    "epsilon": 1e-07, 
    "floatx": "float32", 
    "backend": "tensorflow"
}
You should change "tf" to "th"
